### PR TITLE
Fix incompatibility with PySide in Kali linux. Update .gitignore

### PR DESCRIPTION
**Pull request by alexxn**
This pull request "fixes" problems with Sparta in current Kali linux.
Issues #83 #59 #77 are fixed.

### CODE REVIEW

**Comment by alexxn** [comment]
Also #69. And I forgot to update readme to mention that you have to `apt install python-pyside` now.

**Comment by st3r30byt3** [comment]
Hi Alex,

Many thanks for your contribution.

We are going to try to have a good look at this this week to make sure it doesn't cause any issues and we will merge.

Thanks.

**Comment by st3r30byt3** [comment]
We've included your fix in the latest commit and credited you in the changelog. Thanks! :)

**Comment by hissro** [comment]
Hi all 

still have same problem 

> 
[-] Import failed. PyQt4 library not found. 
Try installing it with: apt install python-qt4
/usr/lib/python2.7/dist-packages/PyQt4/QtGui.x86_64-linux-gnu.so: undefined symbol: _ZN15QSessionManager16staticMetaObjectE
┌─[root@Snake]─[~]

**Pull request closed without merging**
